/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author hello
 */
public class transaction extends javax.swing.JFrame {

    /**
     * Creates new form transaction
     */
    public transaction() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        depositb = new javax.swing.JButton();
        cashwithdrawb = new javax.swing.JButton();
        ministatementb = new javax.swing.JButton();
        pinchangeb = new javax.swing.JButton();
        exitb = new javax.swing.JButton();
        balanceb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Please Select Your Transaction");

        depositb.setText("Deposit");
        depositb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositbActionPerformed(evt);
            }
        });

        cashwithdrawb.setText("Cash Withdrawal");
        cashwithdrawb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashwithdrawbActionPerformed(evt);
            }
        });

        ministatementb.setText("Mini Statement");
        ministatementb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ministatementbActionPerformed(evt);
            }
        });

        pinchangeb.setText("Pin Change");
        pinchangeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinchangebActionPerformed(evt);
            }
        });

        exitb.setText("Exit");
        exitb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbActionPerformed(evt);
            }
        });

        balanceb.setText("Balance Enquiry");
        balanceb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balancebActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(exitb, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(balanceb, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pinchangeb, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                .addComponent(depositb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cashwithdrawb)
                            .addComponent(ministatementb, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashwithdrawb)
                    .addComponent(depositb))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ministatementb)
                    .addComponent(pinchangeb))
                .addGap(43, 43, 43)
                .addComponent(balanceb)
                .addGap(39, 39, 39)
                .addComponent(exitb)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitbActionPerformed

    private void depositbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositbActionPerformed
        // TODO add your handling code here:
         new deposit().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_depositbActionPerformed

    private void cashwithdrawbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashwithdrawbActionPerformed
        // TODO add your handling code here:
         new cash().setVisible(true);
         setVisible(false);
    }//GEN-LAST:event_cashwithdrawbActionPerformed

    private void ministatementbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ministatementbActionPerformed
        // TODO add your handling code heree
        new mini().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_ministatementbActionPerformed

    private void pinchangebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinchangebActionPerformed
        // TODO add your handling code here
        new pinchange().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_pinchangebActionPerformed

    private void balancebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balancebActionPerformed
        // TODO add your handling code here:
        String pinn=JOptionPane.showInputDialog("Enter Your Pin");
         try{
           Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/bankdb","root","Vamshi@31");
           Statement s=c.createStatement();
           ResultSet rs=s.executeQuery("select balance from balancetable where pin='"+pinn+"'");
           if(rs.next()){
               JOptionPane.showMessageDialog(null,"Your balance is "+rs.getString("balance"));
           }
           else
               JOptionPane.showMessageDialog(null,"enter correct pin");
    }
        catch(SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_balancebActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton balanceb;
    private javax.swing.JButton cashwithdrawb;
    private javax.swing.JButton depositb;
    private javax.swing.JButton exitb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton ministatementb;
    private javax.swing.JButton pinchangeb;
    // End of variables declaration//GEN-END:variables
}
